name: aiml25_finalproject_env 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - ipywidgets
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - fastparquet
  - huggingface_hub
  - transformers
  - datasets
  - python-decouple
  - tqdm
  - pre-commit

  # spaCy core + transformers support
  - spacy
  - spacy-transformers

  - pip:
      - ibm-watsonx-ai==1.2.9
      - chromadb
      - duckduckgo-search
      - instructor
      - langchain
      - langchain-chroma
      - langchain-core
      - langchain-ibm
      - langchain-text-splitters
      - langgraph
      - litellm
      - requests
      # spaCy extras
      - spacy-lookups-data

